---
title: "Chapter 27: R Markdown"
output: html_document
---

***

### 27.2.1 Exercises

3. Compare and contrast the R notebook and R markdown files you created above.
How are the outputs similar? How are they different? How are the inputs similar?
How are they different? What happens if you copy the YAML header from one to the
other?

* R notebook files are suitable for capturing what you did, what you were
thinking, and communicating to other data scientists
* R markdown files are suitable for communicating to decision-makers who
don't care about the code
* An R notebook file allows the user to show/hide code and download the file;
an R markdown file does not
* The R markdown file contains additional information in the YAML header
(author and date) by default
* When you copy the YAML header from one to the other it changes the type of
file
    + `output:` determines the type of file that will be created  
 
4. Create one new R Markdown document for each of the three built-in formats:
HTML, PDF and Word. Knit each of the three documents. How does the output differ?
How does the input differ? (You may need to install LaTeX in order to build the
PDF output — RStudio will prompt you if this is necessary.)

* The `output:` set for each of the three formats is different

### 27.3.1 Exercises

See [this repo](https://github.com/benherbertson/cv).

